export const Configuration = Object.freeze({
    DEFAULT_BORROW_DAYS: 'DEFAULT_BORROW_DAYS',
    MAX_BORROW_LIMIT: 'MAX_BORROW_LIMIT',
    DAILY_LATE_FEE: 'DAILY_LATE_FEE',
    LOST_BOOK_PENALTY_RATE: 'LOST_BOOK_PENALTY_RATE'
});